language: dart
# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache

dart:
  - dev
  - stable
script: ./tool/travis.sh
# Use container based builds.
sudo: false
