# Created with package:mono_repo v3.4.1
name: Verify Examples
on:
  push:
    branches:
    - main
  pull_request:
  schedule:
  - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  verify_examples:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: discoveryapis_generator
    steps:
    - name: Cache Pub hosted dependencies
      uses: actions/cache@v2
      with:
        path: "~/.pub-cache/hosted"
        key: "os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:${{ matrix.example_directory }}"
        restore-keys: |
          os:ubuntu-latest;pub-cache-hosted;dart:dev
          os:ubuntu-latest;pub-cache-hosted
          os:ubuntu-latest
    - uses: cedx/setup-dart@v2
      with:
        release-channel: dev
    - uses: actions/checkout@v2
    - run: dart --version
    - id: pub_upgrade
      run: pub upgrade
    - name: Generate Code
      working
      run: |

        dart discoveryapis_generator/bin/generate.dart package -i _test/rest -o _test_package
        dart bin/generate.dart files -i example -o example

    - name: verify output
      run: |
        export DIFF_OUTPUT="$(git diff)"
        if [[ $DIFF_OUTPUT ]]; then
          echo "::error::Build needs to be re-run!"
          echo "::group::git diff"
          echo "$DIFF_OUTPUT"
          echo "::endgroup::"
          exit 1
        else
          echo "Build output is all good!"
        fi
